### ISSUE TITLE
fatal: Needed a single revision

### ISSUE THREAD

**Issue by mirkolai** [Pret-a-LLOD/Fintan#3]
This error appears trying to clone the repository:  **Unable to find current origin/master revision in submodule path 'ui'**

**Comment by cfaeth** [comment]
I cannot replicate this issue. I tried on both Windows with git 2.32.0 and Ubuntu with git 2.25.1 and all submodules resolve just fine.

Did you clone it like this? 

`git clone https://github.com/Pret-a-LLOD/Fintan.git --recurse-submodules`

If it still does not work, there might be some general incompatibility with submodules and your installation. A bit of googling brought me to this thread. Maybe you can find some help there: https://stackoverflow.com/questions/40987847/unable-to-find-current-origin-master-revision-in-submodule-path

**Comment by mirkolai** [comment]
thank you for your quick response,
I tried to run 	

`git clone https://github.com/Pret-a-LLOD/Fintan.git --recurse-submodules --remote-submodules` (as recommended in the README.md file) 

on Ubuntu 20.04 with git 2.25.1

removing the  `--remote-submodules ` option resolves the issue.
Thanks

**Comment by chiarcos** [comment]
I fixed the readme
